export const calloutTypesDefaultColors: { [key: string]: {titleColor: string, titleBgColor: string, contentBgColor: string, contentBorderColor: string, contentColor: string} } = {
    BUG: {
        titleColor: `#ffffff`,
        titleBgColor: `#e93147`,
        contentBgColor: `#e93147`,
        contentBorderColor: `#e93147`,
        contentColor: `#ffffff`,
    },
    DEFAULT: {
        titleColor: `#ffffff`,
        titleBgColor: `#086ddd`,
        contentBgColor: `#086ddd`,
        contentBorderColor: `#086ddd`,
        contentColor: `#ffffff`,
    },
    NOTE: {
        titleColor: `#ffffff`,
        titleBgColor: `#086ddd`,
        contentBgColor: `#086ddd`,
        contentBorderColor: `#086ddd`,
        contentColor: `#ffffff`,
    },
    ERROR: {
        titleColor: `#ffffff`,
        titleBgColor: `#e93147`,
        contentBgColor: `#e93147`,
        contentBorderColor: `#e93147`,
        contentColor: `#ffffff`,
    },
    DANGER: {
        titleColor: `#ffffff`,
        titleBgColor: `#e93147`,
        contentBgColor: `#e93147`,
        contentBorderColor: `#e93147`,
        contentColor: `#ffffff`,
    },
    EXAMPLE: {
        titleColor: `#ffffff`,
        titleBgColor: `#7852ee`,
        contentBgColor: `#7852ee`,
        contentBorderColor: `#7852ee`,
        contentColor: `#ffffff`,
    },
    FAIL: {
        titleColor: `#ffffff`,
        titleBgColor: `#e93147`,
        contentBgColor: `#e93147`,
        contentBorderColor: `#e93147`,
        contentColor: `#ffffff`,
    },
    FAILURE: {
        titleColor: `#ffffff`,
        titleBgColor: `#e93147`,
        contentBgColor: `#e93147`,
        contentBorderColor: `#e93147`,
        contentColor: `#ffffff`,
    },
    MISSING: {
        titleColor: `#ffffff`,
        titleBgColor: `#e93147`,
        contentBgColor: `#e93147`,
        contentBorderColor: `#e93147`,
        contentColor: `#ffffff`,
    },
    IMPORTANT: {
        titleColor: `#ffffff`,
        titleBgColor: `#00bfbc`,
        contentBgColor: `#00bfbc`,
        contentBorderColor: `#00bfbc`,
        contentColor: `#ffffff`,
    },
    INFO: {
        titleColor: `#ffffff`,
        titleBgColor: `#086ddd`,
        contentBgColor: `#086ddd`,
        contentBorderColor: `#086ddd`,
        contentColor: `#ffffff`,
    },
    QUESTION: {
        titleColor: `#ffffff`,
        titleBgColor: `#ec7500`,
        contentBgColor: `#ec7500`,
        contentBorderColor: `#ec7500`,
        contentColor: `#ffffff`,
    },
    HELP: {
        titleColor: `#ffffff`,
        titleBgColor: `#ec7500`,
        contentBgColor: `#ec7500`,
        contentBorderColor: `#ec7500`,
        contentColor: `#ffffff`,
    },
    FAQ: {
        titleColor: `#ffffff`,
        titleBgColor: `#ec7500`,
        contentBgColor: `#ec7500`,
        contentBorderColor: `#ec7500`,
        contentColor: `#ffffff`,
    },
    SUCCESS: {
        titleColor: `#ffffff`,
        titleBgColor: `#08b94e`,
        contentBgColor: `#08b94e`,
        contentBorderColor: `#08b94e`,
        contentColor: `#ffffff`,
    },
    CHECK: {
        titleColor: `#ffffff`,
        titleBgColor: `#08b94e`,
        contentBgColor: `#08b94e`,
        contentBorderColor: `#08b94e`,
        contentColor: `#ffffff`,
    },
    DONE: {
        titleColor: `#ffffff`,
        titleBgColor: `#08b94e`,
        contentBgColor: `#08b94e`,
        contentBorderColor: `#08b94e`,
        contentColor: `#ffffff`,
    },
    SUMMARY: {
        titleColor: `#ffffff`,
        titleBgColor: `#00bfbc`,
        contentBgColor: `#00bfbc`,
        contentBorderColor: `#00bfbc`,
        contentColor: `#ffffff`,
    },
    ABSTRACT: {
        titleColor: `#ffffff`,
        titleBgColor: `#00bfbc`,
        contentBgColor: `#00bfbc`,
        contentBorderColor: `#00bfbc`,
        contentColor: `#ffffff`,
    },
    TLDR: {
        titleColor: `#ffffff`,
        titleBgColor: `#00bfbc`,
        contentBgColor: `#00bfbc`,
        contentBorderColor: `#00bfbc`,
        contentColor: `#ffffff`,
    },
    TIP: {
        titleColor: `#ffffff`,
        titleBgColor: `#00bfbc`,
        contentBgColor: `#00bfbc`,
        contentBorderColor: `#00bfbc`,
        contentColor: `#ffffff`,
    },
    HINT: {
        titleColor: `#ffffff`,
        titleBgColor: `#00bfbc`,
        contentBgColor: `#00bfbc`,
        contentBorderColor: `#00bfbc`,
        contentColor: `#ffffff`,
    },
    TODO: {
        titleColor: `#ffffff`,
        titleBgColor: `#086ddd`,
        contentBgColor: `#086ddd`,
        contentBorderColor: `#086ddd`,
        contentColor: `#ffffff`,
    },
    WARNING: {
        titleColor: `#ffffff`,
        titleBgColor: `#ec7500`,
        contentBgColor: `#ec7500`,
        contentBorderColor: `#ec7500`,
        contentColor: `#ffffff`,
    },
    CAUTION: {
        titleColor: `#ffffff`,
        titleBgColor: `#ec7500`,
        contentBgColor: `#ec7500`,
        contentBorderColor: `#ec7500`,
        contentColor: `#ffffff`,
    },
    ATTENTION: {
        titleColor: `#ffffff`,
        titleBgColor: `#ec7500`,
        contentBgColor: `#ec7500`,
        contentBorderColor: `#ec7500`,
        contentColor: `#ffffff`,
    },
    QUOTE: {
        titleColor: `#ffffff`,
        titleBgColor: `#9e9e9e`,
        contentBgColor: `#9e9e9e`,
        contentBorderColor: `#9e9e9e`,
        contentColor: `#ffffff`,
    },
    CITE: {
        titleColor: `#ffffff`,
        titleBgColor: `#9e9e9e`,
        contentBgColor: `#9e9e9e`,
        contentBorderColor: `#9e9e9e`,
        contentColor: `#ffffff`,
    },
};